---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: {{.Service}}-feature-{{.Release}}
    literals:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-server-{{.Environment}}:5432/{{.Service}}-feature-{{.Release}}?sslmode=verify-full&sslrootcert=/opt/ca/ca.crt
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL95Dialect